version: '3'
services:
  server_rpc:
    build: .
    ports:
      - ${RPC_PORT}:${RPC_PORT}
    container_name: server_geo
    volumes:
      - ".env:/server_app/.env"
    networks:
      - myNetwork 
      - myNetworkDB

  db:
    image: postgres:14.4-alpine
    container_name: postgres_Geo
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
        - 5432:5432
    networks:
      - myNetworkDB

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - myNetworkDB

networks:
  myNetworkDB:
    
  myNetwork:
    name: local